enum EventType {
  GET_TOKENS = "GET_TOKENS",
  SET_TOKENS = "SET_TOKENS",
  SET_COLOR_TOKEN = "SET_COLOR_TOKEN",
  SET_FONT_SIZE_TOKEN = "SET_FONT_SIZE_TOKEN",
  SET_BORDER_RADIUS_TOKEN = "SET_BORDER_RADIUS_TOKEN",
  UPDATE_COLOR_TOKEN = "UPDATE_COLOR_TOKEN",
  UPDATE_FONT_SIZE_TOKEN = "UPDATE_FONT_SIZE_TOKEN",
  UPDATE_BORDER_RADIUS_TOKEN = "UPDATE_BORDER_RADIUS_TOKEN",
  DELETE_TOKEN = "DELETE_TOKEN",
}

export default EventType;
